### ISSUE TITLE
License clarification

### ISSUE THREAD

**Issue by njh** [njh/node-owfs#18]
Hello,

Thank you for transferring the repo to me @benediktarnold. 

Hopefully one final query - you specified the license as 'BSD' - which can refer to many things:
https://spdx.org/licenses/

Do you mind if I switch it to MIT?
https://spdx.org/licenses/MIT.html

It is similar to BSD, very popular/common for node packages and more specific.

Thanks,

nick.

**Comment by benediktarnold** [comment]
MIT is great. My favorite for newer repos. Feel free to change it.

**Comment by njh** [comment]
Thanks!
