### ISSUE TITLE
Writing Error on port XX.XXXXX/PIO.BYTE on DS2408

### ISSUE THREAD

**Issue by jchassin** [njh/node-owfs#25]
When I try to write on my DS2408 port, this raises an error : 
  owfs:communication Sending { path: '/29.09491D000000/PIO.BYTE\u00004',
  command: 3,
  data_len: 1,
  server: 'raspberrypi.local',
  port: '4304' } +25s
  owfs:communication Receiving header { version: 0,
  payload: 0,
  ret: -22,
  controlflags: 32,
  size: 0,
  offset: 0 } +371ms
  owfs:communication Receiving payload  +1ms

If I modify as follow the file owfs, it works:
    Client.prototype.write = function(path, payload, callback) {
      var command;

      command = {
        path: path + "\u0000" + payload,
        command: 3,
        //data_len: payload.toString().length,
        data_len: payload.toString().length+1, // modification performed
        server: this.server,
        port: this.port
      };
      return this.communication.sendCommand(command, callback);

Question 1 : has it been tested with something to write larger than a byte ?
Comment: I did not fully understand the code here so I am pretty sure the fix here is not properly done, do you have any advice ?

tks,
jean

**Comment by njh** [comment]
No, actually, I think I have only tested with single-byte writes.

Sadly I don't have a DS2408. But it should be possible to emulate a DS2408 using:

```bash
owserver \
  --foreground \
  --error_print=2 \
  --error_level=4 \
  --fake=DS2408
```

The payload object that you have referenced above should probably be a Buffer, rather than a string. The protocol specification is here:

http://owfs.org/index.php?page=owserver-protocol


Please can you tell me the equivalent ```owwrite``` command that you were trying to run?

Thanks for reporting.

**Comment by njh** [comment]
Hi @jchassin,

I am going try try and fix this for the next release. While I still don't have a DS2408 device, I was seeing problems when I was trying to use a fake/virtual DS2408 with owserver.

I have been looking at the DS2408 man page from owfs:
http://owfs.org/index.php?page=ds2408

It says that PIO.BYTE should only take a single byte...

nick.

**Comment by jchassin** [comment]
Hi @njh,

It's been a long time I did not come here, unfortunally, I don't have more detail on this. I wanted to set one output on my DS2408 when this error occured.

Maybe, the code that were using your library can help ?
https://github.com/jchassin/homebridge-owfs/commit/e31450e0ac0778ede5b549283aca44fb7e3f2183

Tell me,
Regards,
Jean

**Comment by njh** [comment]
Ok, thanks. I think I have enough to fix this.

**Comment by njh** [comment]
I believe I have fixed this in 15be0244e4a2005041b7c975ccbe25fda5732038

When comparing the request sent with what `owwrite` was sending, there was an extra null byte on the end of the payload. Removing it made my integration test pass.

However I don't own a DS2408 to test with some real hardware.

**Comment by njh** [comment]
Closing this, as I believe it is fixed. Please re-open if it is still an issue.

Just about to release version 0.3.2.

**Comment by jchassin** [comment]
Many thanks, I'll try it as soon as I can
Jean
